### ISSUE TITLE
I got this error: Error: C stack usage  7954432 is too close to the limit

### ISSUE THREAD

**Issue by Memk55** [john-harrold/ubiquity-pkpd#1]
When I tries to test the codes as follow:
install.packages("ubiquity")
library(ubiquity)
"fr <- workshop_fetch(section="NCA", overwrite=TRUE)
cfg <- build_system(system_file="system.txt")
cfg <- system_load_data(cfg, dsname     = "PKDATA", 
                       data_file  = "pk_all_sd.csv")
cfg = system_nca_run(cfg,  dsname        = "PKDATA", 
                     dscale        = 1e6, 
                     analysis_name = "pk_single_dose", 
                     extrap_C0     = FALSE, 
                     dsmap         = list(TIME    = "TIME_HR", 
                                          NTIME   = "TIME_HR", 
                                          CONC    = "C_ng_ml", 
                                          DOSE    = "DOSE",
                                          ROUTE   = "ROUTE", 
                                          ID      = "ID"),
                     NCA_options   = list(max.aucinf.pext  = 10) )"

I got this error: "C stack usage  7954432 is too close to the limit" after the command "cfg <- build_system(system_file="system.txt")" . Could you please help me how to fix this issue please? Thanks!

**Comment by john-harrold** [comment]
That error generally occurs in R when there is some kind of loop (like a while loop) with no exit condition. I know that probably doesn't tell you much, but that's where I've seen it in the past.

Can you do the following:

Take a screenshot of everything that you get leading up to that error. I'm wondering if there are any other warnings or messages that may be helpful.

Can you also include the output of  sessionInfo() after you get the error so I can see the versions of everything that's loaded?

**Comment by Memk55** [comment]
Hi John-Harrold,

Thanks so much for your response.
Attached here are the screenshots of everything that I did leading me to
the error. And also the output of sessioninfo.
Hopefully, they will help to find out the answer to this issue.

Kind regards,

Hue

**Comment by john-harrold** [comment]
Hello Hue,

I don't see any attachments. If you replied by email and attached them I don't think they made it through. You an attach them to the comment on GitHub or email them directly to me (john dot m dot harrold _at_ gmail dot com).

**Comment by Memk55** [comment]
Hi John,

I have just sent them directly to your gmail.

Kind regards,

Hue

**Comment by john-harrold** [comment]
This was a weird M1 mac issue that I believe has been resolved.
